# Generated by Django 3.1 on 2022-10-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='UpdationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
