# Generated by Django 3.1 on 2022-10-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0002_auto_20221022_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='AssignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firereport.teams'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='AssignedTime',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='FullName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='MobileNumber',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='Status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamLeadMobno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamLeaderName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamMembers',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
